name:                hello-world
version:             1.0.0.0
license:             MIT
author:              PSYOP
maintainer:          admin@psyop.ca
copyright:           2025 PSYOP
homepage:            https://psyop.ca

synopsis:            A simple hello world application
category:            Hello World, Example

description: |
  A minimal hello world application.
  
  This is a clean, simple package that demonstrates basic functionality.

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

executables:
  hello-world:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - hello-world

library:
  source-dirs: src

tests:
  hello-world-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hello-world
    - hspec
