name:                psyop-website
version:             0.2.0.0
github:              "Shahzebqazi/psyop.ca"
license:             BSD-3-Clause
author:              "PSYOP"
maintainer:          "admin@psyop.ca"
copyright:           "2025 PSYOP"
homepage:            "https://psyop.ca"
bug-reports:         "https://github.com/Shahzebqazi/psyop.ca/issues"
synopsis:            "PSYOP Electronic Music Website with Enhanced Development Environment"
description: "PSYOP Electronic Music Website - A modern, dynamic website featuring dynamic backgrounds, Lovecraftian transitions, and advanced image sequence management. Includes enhanced development environment with auto-reload, project setup, and comprehensive tooling. Features ./stack-dev script for familiar Stack-like development commands."
category:            Web, Music, Electronic
extra-source-files:
- LICENSE
- env.template
- css/*
- public/*
- config/*
- assets/white/*
- assets/red_white/*

dependencies:
- base >= 4.7 && < 5
- wai
- wai-cors
- warp
- servant
- servant-server
- blaze-html
- text
- bytestring
- http-types
- directory
- filepath
- wai-extra

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# Development Commands
# Use ./stack-dev for familiar Stack-like experience

library:
  source-dirs:         src
  exposed-modules:
    - Lib

executables:
  psyop-website-exe:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - psyop-website
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  


tests:
  psyop-website-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - psyop-website
    - hspec
    - hspec-wai
    - wai
    - http-types
    ghc-options:
    - -Wall
