name:                psyop-website
version:             0.3.1.0
github:              "Shahzebqazi/psyop.ca"
license:             BSD-3-Clause
author:              "Psyop"
maintainer:          "admin@psyop.ca"
copyright:           "2025 Psyop"
homepage:            "https://psyop.ca"
bug-reports:         "https://github.com/Shahzebqazi/psyop.ca/issues"
synopsis:            "Electronic music website with WebGL background system"
description:         "Modern electronic music website featuring WebGL-powered dynamic backgrounds, shader-based transitions, and responsive design. See README.md for full documentation."
category:            Web, Music, Electronic, WebGL
extra-source-files:
- LICENSE
- assets/*
- assets/graphics/*
- assets/graphics/white/*
- assets/graphics/red_white/*
- assets/webdev/icons/streaming/*

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- warp-tls
- yaml
- aeson
- blaze-html
- text
- bytestring
- http-types
- case-insensitive
- filepath
- directory
- time
- containers
- random

library:
  source-dirs:         src
  exposed-modules:
    - 
    - Models
    - App

executables:
  psyop-website-exe:
    main:                Main.hs
    source-dirs:         src
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - psyop-website

tests:
  psyop-website-test:
    main:                Spec.hs
    source-dirs:         Tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - psyop-website
    - base
    - hspec
    - text
    - wai
    - http-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
