name:                psyop-website
version:             0.1.0.0
github:              "githubuser/psyop-website"
license:             BSD-3-Clause
author:              "${PACKAGE_AUTHOR:-PSYOP}"
maintainer:          "${PACKAGE_MAINTAINER:-admin@psyop.ca}"
copyright:           "${PACKAGE_COPYRIGHT:-2025 PSYOP}"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/psyop-website#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-blaze
- wai
- warp
- blaze-html
- blaze-markup
- text
- bytestring
- containers
- mtl
- transformers
- JuicyPixels
- JuicyPixels-extra
- directory
- filepath


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  psyop-website-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - psyop-website

  image-optimizer:
    main:                ImageOptimizer.hs
    source-dirs:         tools
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - psyop-website

tests:
  psyop-website-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - psyop-website
    - hspec
    - hspec-wai
    - wai-extra
    - http-types
