site:
  name: "Psyop"
  subtitle: "lite edition"
  hero_image: "assets/graphics/white/promo_1.jpg"
  bio: |
    Psyop (ˈsaɪ.ɑp) is a 4 piece Metal Machine from Toronto, Canada.
    Rooted in nu‑metal foundations with addictive hooks and ruthless breakdowns.
    Psyop is James, Max, Miles and Willy.
  social_links:
    - { label: "Instagram", url: "https://instagram.com/psyopband" }
    - { label: "TikTok", url: "https://tiktok.com/@psyopsucks" }
    - { label: "Spotify", url: "https://open.spotify.com/artist/2bRWBW2Km3N9MSXY90QKb7?si=oVutT8ZFTxylihcAk-_sHg" }
  random_definitions_file: "psyop.txt"

