name: Deploy PSYOP Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.10.1.0'
        
    - name: Build application
      run: |
        stack build
        
    - name: Test application
      run: |
        stack test
        
    - name: Notify deployment
      run: |
        echo "Deployment triggered for branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        
    - name: Trigger webhook (optional)
      if: github.event_name == 'push'
      run: |
        # This step can trigger a webhook to your server
        # You can use curl to ping your webhook endpoint
        echo "Webhook deployment triggered automatically"
        
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "✅ Deployment successful"
        else
          echo "❌ Deployment failed"
        fi
